// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4P2RnA6_RMQxN5tQDXUYnY6XcVS5VlA',
    appId: '1:229610582553:web:1f24342f87eee688b2b088',
    messagingSenderId: '229610582553',
    projectId: 'ai-hackathon-460510',
    authDomain: 'ai-hackathon-460510.firebaseapp.com',
    storageBucket: 'ai-hackathon-460510.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApBN2o-qym_-e0JwlSLswJ2i0nbtkZvKA',
    appId: '1:229610582553:android:ac296c4e2e4574e3b2b088',
    messagingSenderId: '229610582553',
    projectId: 'ai-hackathon-460510',
    storageBucket: 'ai-hackathon-460510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wYJy0LufzOe3h9TJo4EMoH08ssnWZOg',
    appId: '1:229610582553:ios:bd5ffef72e7c4485b2b088',
    messagingSenderId: '229610582553',
    projectId: 'ai-hackathon-460510',
    storageBucket: 'ai-hackathon-460510.firebasestorage.app',
    iosBundleId: 'com.example.flutterClient',
  );
}
